// Enumerazione dei bookmakers per le quote di Robin

const RobinOddsBookmakersEnum: { [key: number]: string } = {
    2: 'Bet365',
    21: 'Planetwin365',
    36: 'Betfair Exchange',
    6: 'Betflag Exchange',
    14: '888',
    28: 'AdmiralBet',
    3: 'Betaland',
    4: 'Betclic',
    5: 'Betfair Sportsbook',
    7: 'Betflag Sportsbook',
    9: 'Better/Lottomatica',
    11: 'Betway',
    10: 'Bwin',
    27: 'DaznBet',
    12: 'Domusbet',
    43: 'Efbet',
    13: 'Eurobet',
    16: 'Goldbet',
    18: 'LeoVegas',
    1: 'Marathonbet',
    23: 'NewGioco',
    39: 'Novibet',
    25: 'Pinnacle',
    20: 'PinterBet',
    22: 'Plexbet',
    8: 'PokerStars',
    24: 'Sisal',
    26: 'Snai',
    37: 'SportBet',
    38: 'SportItaliaBet',
    30: 'Stanleybet',
    29: 'StarVegas',
    35: 'TerryBet',
    32: 'Unibet',
    44: 'VinciTu',
    33: 'William Hill',
    40: 'WinBet',
    42: 'ZonaGioco',
};

export default RobinOddsBookmakersEnum;
